.TH SMOF "1"

.SH NAME
smof-<subcommand> \- <description>

.SH SYNOPSIS
.B smof <subcommand>
[\fIOPTION\fR]... [\fIFILE\fR]...

.SH DESCRIPTION
.PP
<long description>

.SH OPTIONS

.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
output version information and exit
.PP

<other help messages>

.SH EXAMPLES

<example 1>
.sp
.RS 4
.nf
\fB
<code>
.fi \fR
.P
.RE
.P

.SH SEE ALSO

smof(1), smof-clean(1), smof-filter(1), smof-grep(1), smof-md5sum(1),
smof-head(1), smof-permute(1), smof-reverse(1), smof-sample(1), smof-sniff(1),
smof-sort(1), smof-split(1), smof-stat(1), smof-subseq(1), smof-tail(1),
smof-uniq(1), smof-wc(1)

.SH AUTHOR
Written by Zebulun Arendsee.

.SH "REPORTING BUGS"
Github: <https://github.com/zbwrnz/smof>

.SH COPYRIGHT

Copyright (C) 2016 Zebulun Arendsee (smof)
License: GNU GPL
