.TH SMOF "1"

.SH NAME
smof \- manipulate FASTA format data

.SH SYNOPSIS
.B smof 
[--version] [--help] [\fISUBCOMMAND\fR] [\fIOPTION\fR]... [\fIFILE\fR]...

.SH DESCRIPTION
.PP
\fBsmof\fR is the namespace for a suite of tools all designed to manipulate FASTA formated data.
.PP
With no FILE read standard input. \fBsmof\fR always writes to standard output.

.SH OPTIONS

.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
output version information and exit
.PP

.SH SMOF SUBCOMMANDS

.B clean
.RS 4
cleans fasta files
.RE
.PP

.B filter
.RS 4
extracts sequences meeting the given conditions
.RE
.PP

.B grep
.RS 4
roughly emulates the UNIX grep command
.RE
.PP

.B md5sum
.RS 4
calculate an md5 checksum for the input sequences
.RE
.PP

.B head
.RS 4
writes the first sequences in a file
.RE
.PP

.B permute
.RS 4
randomly order sequence
.RE
.PP

.B reverse
.RS 4
reverse each sequence (or reverse complement)
.RE
.PP

.B sample
.RS 4
randomly select entries from fasta file
.RE
.PP

.B sniff
.RS 4
extract info about the sequence
.RE
.PP

.B sort
.RS 4
sort sequences
.RE
.PP

.B split
.RS 4
split a fasta file into smaller files
.RE
.PP

.B stat
.RS 4
calculate sequence statistics
.RE
.PP

.B subseq
.RS 4
extract subsequence from each entry (revcomp if a<b)
.RE
.PP

.B tail
.RS 4
writes the last sequences in a file
.RE
.PP

.B uniq
.RS 4
count, omit, or merge repeated entries
.RE
.PP

.B wc
.RS 4
roughly emulates the UNIX wc command
.RE
.PP

.SH EXAMPLES

Get a list of all subcommands and their brief descriptions
.sp
.RS 4
.nf
\fB
smof -h
.fi \fR
.P
.RE
.P

Get brief help with one subcommand
.sp
.RS 4
.nf
\fB
smof grep -h
.fi \fR
.P
.RE
.P

Get full documentation of one subcommand
.sp
.RS 4
.nf
\fB
man smof-grep
.fi \fR
.P
.RE
.P

Build a simple smof pipeline
.sp
.RS 4
.nf
\fB
smof clean -x a.fasta | smof grep -qoP 'TATA..' | grep -v '>' | sort | uniq -c
.fi \fR
.P
.RE
.P

.SH SEE ALSO

smof-clean(1), smof-filter(1), smof-grep(1), smof-md5sum(1), smof-head(1),
smof-permute(1), smof-reverse(1), smof-sample(1), smof-sniff(1), smof-sort(1),
smof-split(1), smof-stat(1), smof-subseq(1), smof-tail(1), smof-uniq(1),
smof-wc(1)

.SH AUTHOR
Written by Zebulun Arendsee.

.SH "REPORTING BUGS"
Github: <https://github.com/zbwrnz/smof>

.SH COPYRIGHT

Copyright (C) 2016 Zebulun Arendsee (smof)
License: GNU GPL
